//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalDisastersAPIFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarthQuakeTable
    {
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<decimal> Magnitude { get; set; }
        public string Place { get; set; }
        public int EarthquakeID { get; set; }
    }
}
